CREATE TABLE conserto (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          data_entrada VARCHAR(10) NOT NULL,
                          data_saida   VARCHAR(10) NOT NULL,

    -- Mecanico
                          nome               VARCHAR(120) NOT NULL,
                          anos_experiencia   VARCHAR(10)  NOT NULL,

    -- Veiculo
                          marca  VARCHAR(60) NOT NULL,
                          modelo VARCHAR(60) NOT NULL,
                          ano    VARCHAR(4)  NOT NULL,
                          cor varchar(20)
);