CREATE TABLE conserto (
                          id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          data_entrada                VARCHAR(10) NOT NULL,
                          data_saida                  VARCHAR(10),
                          mecanico_nome               VARCHAR(120) NOT NULL,
                          mecanico_anos_experiencia   INT,
                          veiculo_marca               VARCHAR(80)  NOT NULL,
                          veiculo_modelo              VARCHAR(120) NOT NULL,
                          veiculo_ano                 CHAR(4)      NOT NULL

);